import React, { useState } from "react";
import { useStudioState } from "../../state/studioState";
import type { Transaction } from "../../state/transactions";

type AccordionId =
  | "chat"
  | "tool-log"
  | "scene-diff"
  | "transactions"
  | "validation"
  | "alternatives"
  | "action-graph";

const ACCORDIONS: Array<{ id: AccordionId; label: string; placeholder: string }> = [
  {
    id: "chat",
    label: "Chat",
    placeholder: "Sprint 6 wires the chat transport. Drafts will be model/provider agnostic — config-driven.",
  },
  {
    id: "tool-log",
    label: "Tool Call Log",
    placeholder: "Streamed agent tool calls (read_scene, mutate_transform, add_component, …) appear here.",
  },
  {
    id: "scene-diff",
    label: "Scene Diff",
    placeholder: "Pending agent transactions render an Apply/Reject diff overlay in the viewport.",
  },
  {
    id: "transactions",
    label: "Transaction History",
    placeholder: "",
  },
  {
    id: "validation",
    label: "Validation",
    placeholder: "Agent-suggested validations land here before being promoted to the Validation drawer.",
  },
  {
    id: "alternatives",
    label: "Alternatives",
    placeholder: "Variant A/B/C generated by the agent; click to preview live in the viewport.",
  },
  {
    id: "action-graph",
    label: "Action Graph",
    placeholder: "V2 — visual graph of agent reasoning steps + tool dependencies.",
  },
];

export type AgentWorkbenchProps = {
  transactions?: Transaction[];
};

export const AgentWorkbench: React.FC<AgentWorkbenchProps> = ({ transactions = [] }) => {
  const { state, toggleAgentPanel } = useStudioState();
  const [openAccordion, setOpenAccordion] = useState<AccordionId>("chat");

  if (!state.agentPanelOpen) return null;

  return (
    <aside className="agent-panel" aria-label="Agent Workbench">
      <header className="agent-panel__header">
        <span>◐ Agent Workbench</span>
        <button
          type="button"
          className="panel-header__btn"
          onClick={toggleAgentPanel}
          title="Close (F12)"
        >×</button>
      </header>
      <div className="agent-panel__body">
        {ACCORDIONS.map((acc) => {
          const isOpen = openAccordion === acc.id;
          const badge =
            acc.id === "transactions" && transactions.length > 0
              ? transactions.length
              : null;

          return (
            <section key={acc.id} className="agent-accordion">
              <button
                type="button"
                className={`agent-accordion__header ${isOpen ? "is-open" : ""}`}
                onClick={() => setOpenAccordion(isOpen ? "chat" : acc.id)}
              >
                <span>{acc.label}</span>
                {badge !== null && (
                  <span className="agent-accordion__badge">{badge}</span>
                )}
                <span className="agent-accordion__chevron" aria-hidden>
                  {isOpen ? "▾" : "▸"}
                </span>
              </button>

              {isOpen && (
                <div className="agent-accordion__body">
                  {acc.id === "transactions" ? (
                    transactions.length === 0 ? (
                      <p className="tx-empty">No transactions yet.</p>
                    ) : (
                      <ul className="tx-list">
                        {transactions.map((tx) => (
                          <li key={tx.id} className={`tx-row tx-row--${tx.source}`}>
                            <span className="tx-row__id">{tx.id}</span>
                            <span className="tx-row__desc">{tx.description}</span>
                            <span className="tx-row__time">
                              {new Date(tx.timestamp).toLocaleTimeString([], {
                                hour: "2-digit",
                                minute: "2-digit",
                                second: "2-digit",
                              })}
                            </span>
                          </li>
                        ))}
                      </ul>
                    )
                  ) : (
                    <>
                      <span className="agent-pill">stub</span>
                      <p style={{ margin: "8px 0 0", lineHeight: 1.4 }}>{acc.placeholder}</p>
                    </>
                  )}
                </div>
              )}
            </section>
          );
        })}
      </div>
    </aside>
  );
};
