import React, { useState } from "react";
import { useStudioState } from "../../state/studioState";

/**
 * Agent Workbench — 360px right dock, F12 toggle.
 *
 * Per DESIGN_LANGUAGE §10.5, the panel hosts 7 accordions:
 *   Chat / Tool Call Log / Scene Diff / Transaction History / Validation /
 *   Alternatives / Action Graph (V2 feature flag)
 *
 * Sprint 2 lands the accordion shell + empty-state copy. Sprint 6 wires the
 * actual chat transport, tool-call log streaming, scene-diff overlay, and
 * transaction history (depends on Sprint 5 transaction store).
 */

type AccordionId =
  | "chat"
  | "tool-log"
  | "scene-diff"
  | "transactions"
  | "validation"
  | "alternatives"
  | "action-graph";

const ACCORDIONS: Array<{ id: AccordionId; label: string; placeholder: string }> = [
  {
    id: "chat",
    label: "Chat",
    placeholder: "Sprint 6 wires the chat transport. Drafts will be model/provider agnostic — config-driven.",
  },
  {
    id: "tool-log",
    label: "Tool Call Log",
    placeholder: "Streamed agent tool calls (read_scene, mutate_transform, add_component, …) appear here.",
  },
  {
    id: "scene-diff",
    label: "Scene Diff",
    placeholder: "Pending agent transactions render an Apply/Reject diff overlay in the viewport.",
  },
  {
    id: "transactions",
    label: "Transaction History",
    placeholder: "T-NNN entries with before/after, affected objects, and rollback affordance.",
  },
  {
    id: "validation",
    label: "Validation",
    placeholder: "Agent-suggested validations land here before being promoted to the Validation drawer.",
  },
  {
    id: "alternatives",
    label: "Alternatives",
    placeholder: "Variant A/B/C generated by the agent; click to preview live in the viewport.",
  },
  {
    id: "action-graph",
    label: "Action Graph",
    placeholder: "V2 — visual graph of agent reasoning steps + tool dependencies.",
  },
];

export const AgentWorkbench: React.FC = () => {
  const { state, toggleAgentPanel } = useStudioState();
  const [openAccordion, setOpenAccordion] = useState<AccordionId>("chat");

  if (!state.agentPanelOpen) return null;

  return (
    <aside className="agent-panel" aria-label="Agent Workbench">
      <header className="agent-panel__header">
        <span>◐ Agent Workbench</span>
        <button
          type="button"
          className="panel-header__btn"
          onClick={toggleAgentPanel}
          title="Close (F12)"
        >×</button>
      </header>
      <div className="agent-panel__body">
        {ACCORDIONS.map((acc) => {
          const isOpen = openAccordion === acc.id;
          return (
            <section key={acc.id} className="agent-accordion">
              <button
                type="button"
                className={`agent-accordion__header ${isOpen ? "is-open" : ""}`}
                onClick={() => setOpenAccordion(isOpen ? "chat" : acc.id)}
              >
                <span>{acc.label}</span>
                <span className="agent-accordion__chevron" aria-hidden>{isOpen ? "▾" : "▸"}</span>
              </button>
              {isOpen && (
                <div className="agent-accordion__body">
                  <span className="agent-pill">stub</span>
                  <p style={{ margin: "8px 0 0", lineHeight: 1.4 }}>{acc.placeholder}</p>
                </div>
              )}
            </section>
          );
        })}
      </div>
    </aside>
  );
};
